In [1]:
import numpy as np

## Importing/Writing .txt and csv .files 

### Reading

In [8]:
textfile = np.loadtxt('text.txt', delimiter='-')
print(textfile)

# For CSV it only recognize the numerical data and other info would be nan
csvfile=np.genfromtxt('test.csv',delimiter=',')
print(csvfile)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[[nan nan nan nan nan]
 [nan 22. nan nan nan]
 [nan 25. nan nan nan]
 [nan 30. nan nan nan]
 [nan 27. nan nan nan]]


### Writing

In [12]:
newdata = textfile*2
np.savetxt('Newtxt.txt',newdata,delimiter=',')
np.savetxt('newCSV',csvfile[1:,1],delimiter=',')

## Array Definition

### One Dimensional

In [13]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

### Two Dimensional

In [14]:
arr2= np.array([(1,2,3),(4,5,6)])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

### Four Dimensional

It is a 2* 2* 2* 2 array (4 Dimensions). 2 list contains 2 list which contains 2 list containing 2 other list!

In [ ]:
arr3 = np.array([[[[1, 2], [3, 4]],[[5, 6], [7, 8]]],[[[9, 10], [11, 12]],[[13, 14], [15, 16]]]])
arr3

## Useful array Creator Commands